apiVersion: apps/v1
kind: Deployment
metadata:
  name: abhay-deploy
  labels:
    app: abhay-mvn-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abhay-mvn-app
  template:
    metadata:
      labels:
        app: abhay-mvn-app
    spec:
      containers:
      - name: abhay-mvn-container
        image: abhay/abhaydevops:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abhay-np-service
  labels:
    app: abhay-mvn-app
spec:
  selector:
    app: abhay-mvn-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
